config/routes.rb
Rails.application.routes.draw do
  resources :articles do 
     member do
        put 'favourites'
        delete 'favourites'
     end  
   end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "signup" => "signup#new"
  post "signup" => "signup#create"
  get "signin" => "session#new"
  post "signin" => "session#create"
  delete "signout" => "session#destroy"
  get "favourite_articles" => "user#my_favourite"
  get "all_user" => "user#index"
  put "follow" => "user#follow"
  delete "unfollow" => "user#unfollow"
  get "followees_articles" => "user#my_followees_articles"
  get "my_followers_list" => "user#my_followers_list"
  get "my_followed_list" => "user#my_followed_list"


   # Api Routes
   namespace :api do
    namespace :v1 do
      resources :articles do 
        member do
           put 'favourites'
           delete 'favourites'
        end  
      end
      post "signup" => "signup#create"
      get "users" => "user#index"
      post "signin" => "authentication#authenticate" 
      get "favourite_articles" => "user#my_favourite"
      put "follow" => "user#follow"
      delete "unfollow" => "user#unfollow"
      get "followees_articles" => "user#my_followees_articles"
      get "my_followers_list" => "user#my_followers_list"
      get "my_followed_list" => "user#my_followed_list"
    end
  end


  root to: 'articles#index'
end

app/models/article.rb
class Article < ApplicationRecord

    has_many :favourites
    belongs_to :user
    has_many :likers, :through => :favourites, :source => :user
    validates :title,:content, presence: true
end

app/controllers/api/v1/articles_controller.rb
class Api::V1::ArticlesController < Api::V1::ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy, :favourites]
  before_action :allowed_user , only: %i[destroy update edit]
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
    render json: {data: @articles}
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    render json: {data: @article}
  end


  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    @article.user_id= @current_user.id
   
      if @article.save
        render json: {data: @article , message: 'article is successfuly added'}
      else
        render json: { message: 'article is Unsuccessfuly added'}
      end
    
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
      if @article.update(article_params)
        render json: {data: @article , message: 'article is successfuly updated'}
      else
        render json: { message: 'article is Unsuccessfuly added'}

      end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    render json: { message: 'article is deleted successfuly added'}

  end
  
  

  def favourites
    if @article.likers.include? @current_user
        @article.likers.delete(@current_user)
        @article.count-=1
        render json: {data: @article , message: 'article is successfuly removed from favourite'}
    else
        @article.likers<<@current_user
        @article.count+=1
        @article.save
        render json: {data: @article , message: 'article is successfuly added to favourite'}
    end
    @article.save  
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.permit(:title, :content)
    end

  
    
    def allowed_user
      if @current_user.id != @article.user_id
        render json: { message: 'you are not authorized'}

      end
    end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy, :add_favourite, :remove_favourite, :favourites]
  before_action :current_user ,:authorized_user
  before_action :allowed_user , only: %i[destroy update edit]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    @article.user_id= @current_user.id
    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def favourites
    if @article.likers.include? @current_user
        @article.likers.delete(@current_user)
        @article.count-=1
        notice = "Article #{@article.title} successfully removed from favourites."
    else
        @article.likers<<@current_user
        @article.count+=1
        notice = "Article #{@article.title} successfully added to favourites."
      end
    @article.save
    redirect_back fallback_location: article_path , notice: notice
  
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :content)
    end

    def authorized_user
      if @current_user.blank?
        redirect_to ('/signin')
      end
    end

    
    def allowed_user
      if @current_user.id != @article.user_id
         respond_to do |format|
          format.html {redirect_to articles_path, notice: 'You are not authorized' }
         end
      end
    end

end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.content %></td>
        <td><%= article.user.email %></td>
        <td><%= link_to 'Show', article %></td>
        <% if @current_user.id == article.user_id%>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %>
        <%end%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @article.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @article.user.email %>
</p>

<p>
  <strong>Favouriets Count:</strong>
  <%= @article.count %>
</p>

<%if !@article.likers.include? @current_user%>
<%= link_to 'Add to favourites', favourites_article_path(@article),method: :put %>
<%else%>
<%= link_to 'Remove from favourites', favourites_article_path(@article) ,method: :delete, data: { confirm: 'Are you sure to remove it from favourite?'} %>
<%end%>
<%if @current_user.id == @article.user_id%>
<%= link_to 'Edit', edit_article_path(@article) %> |
<%end%>
<%= link_to 'Back', articles_path %>