config/routes.rb
Rails.application.routes.draw do
  resources :articles do 
     member do
        put 'favourites'
        delete 'favourites'
     end  
   end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "signup" => "signup#new"
  post "signup" => "signup#create"
  get "signin" => "session#new"
  post "signin" => "session#create"
  delete "signout" => "session#destroy"
  get "favourite_articles" => "user#my_favourite"
  get "all_user" => "user#index"
  put "follow" => "user#follow"
  delete "unfollow" => "user#unfollow"
  get "followees_articles" => "user#my_followees_articles"
  get "my_followers_list" => "user#my_followers_list"
  get "my_followed_list" => "user#my_followed_list"


   # Api Routes
   namespace :api do
    namespace :v1 do
      resources :articles do 
        member do
           put 'favourites'
           delete 'favourites'
        end  
      end
      post "signup" => "signup#create"
      get "users" => "user#index"
      post "signin" => "authentication#authenticate" 
      get "favourite_articles" => "user#my_favourite"
      put "follow" => "user#follow"
      delete "unfollow" => "user#unfollow"
      get "followees_articles" => "user#my_followees_articles"
      get "my_followers_list" => "user#my_followers_list"
      get "my_followed_list" => "user#my_followed_list"
    end
  end


  root to: 'articles#index'
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates_presence_of :password_digest
    validates :email, presence: true, uniqueness: true
    validates_format_of :email, :with =>/.+@[a-zA-Z]+\..+/i	
   
    has_many :favourites
    has_many :favourite_articles, :through => :favourites, :source => :article
    has_many :articles

    #Has_many | Has_many — Self Join Table
    has_many :follower_follows, foreign_key: :followee_id, class_name: "Follow"
    has_many :followers, through: :follower_follows, source: :follower
   

    has_many :followee_follows, foreign_key: :follower_id, class_name: "Follow"
    has_many :followees, through: :followee_follows, source: :followee
    
end

app/controllers/api/v1/user_controller.rb
# frozen_string_literal: true
class Api::V1::UserController < Api::V1::ApplicationController
 

  def index
    @users = User.all
    render json:  @users

  end

  def my_favourite
    # user = User.find(@current_user.id)
    @favourites = @current_user.favourite_articles
    render json: @favourites
  end

  def follow
      
    user = User.find_by(id: params[:id])
    if user
      if user.id != @current_user.id
        if !user.followers.include? @current_user
        user.followers << @current_user
        @current_user.count_followees += 1
        user.count_followers += 1
        user.save
        @current_user.save

        render json: {message: 'Followed Succesfully'}
        else 
          render json: {message: 'already followed'}
        end
      else
        render json:{message:  "You Can't Follow your self"}
      end
    else
      render json: {message: 'User not found'}
    end
  end

  def unfollow
    user = User.find_by(id: params[:id])
    if user
      if user.id != @current_user.id
        if user.followers.include? @current_user
          user.followers.delete(@current_user)
          @current_user.count_followees -= 1
          user.count_followers -= 1
          user.save
          @current_user.save
          render json:{message: 'Unfollowed Succesfully'}
        else 
          render json: {message: 'already unfollowed'}
        end
      else
        render json: {message: "You Can't Unfollow your self"}
      end
    else
      render json:{message: "User not found"}

    end
  end


  def my_followees_articles
     @data=[]
     @followees=@current_user.followees
     @followees.each do |followee|
      followee.articles.each do |article|
        @data<<article
      end
     end
    render json: {data: @data }

  end

  def my_followers_list
    @followers_list=@current_user.followers
    render json:  {data: @followers }

  end

  def my_followed_list
    @followed_list=@current_user.followees
    render json:  {data: @followed_list }
  end

end

app/controllers/user_controller.rb
# frozen_string_literal: true

class UserController < ApplicationController
  before_action :current_user , :authorized_user

  def index
    @users = User.all
  end

  def my_favourite
    # user = User.find(@current_user.id)
    @favourites = @current_user.favourite_articles
  end

  def follow
    # user = User.where(id: params[:id])
    # if user.count > 0
      
    user = User.find_by(id: params[:id])
    if user
      if user.id != @current_user.id
        if !user.followers.include? @current_user
          user.followers << @current_user
          @current_user.count_followees += 1
          user.count_followers += 1
          user.save
          @current_user.save
          notice="Followed Succesfully"   
        else
          notice="already Followed"
        end
      else
        notice="You Can't Follow your self"
      end
    else
     notice = "User not found"
    end
    respond_to do |format|
      format.html { redirect_back fallback_location: all_user_url, notice: notice}
    end
  end

  def unfollow
      user = User.find_by(id: params[:id])
      if user
        if user.id != @current_user.id
          if user.followers.include? @current_user
            user.followers.delete(@current_user)
            @current_user.count_followees -= 1
            user.count_followers -= 1
            user.save
            @current_user.save
            notice="Unfollowed Succesfully"
          else
            notice="already Unfollowed"         
          end
        else
          notice="You Can't Unfollow your self" 
        end
      else  
        notice="User not found"
      end
      respond_to do |format|
        format.html { redirect_back fallback_location: all_user_url, notice: notice }
      end
  end


  def my_followees_articles
    # @followees=@current_user.followees
    @articles=[]
    @followees=@current_user.followees
    @followees.each do |followee|
     followee.articles.each do |article|
       @articles<<article
     end
    end
  end

  def my_followers_list
    @followers_list=@current_user.followers
  end

  def my_followed_list
    @followed_list=@current_user.followees
  end

  private

  def authorized_user
    redirect_to '/signin' if @current_user.blank?
    end

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>user</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
      <%if @current_user.id!=user.id%>
        <td><%= user.email%></td>
        <%if !@current_user.followees.include? user%>
        <td><%= link_to 'follow', follow_path(:id=>user.id),method: :put%> </td>
        <%else%> 
        <td><%= link_to 'unfollow', unfollow_path(:id=>user.id),method: :delete, data: { confirm: 'Are you sure?' }%> </td> 
        <%end%>
      <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/user/my_favourite.html.erb
 <hr>
 <% @favourites.each do |article| %>
   <strong>Content:</strong> <%=article.content%> <br>
   <strong stlye="margin-left:30px">Title:</strong> <%=article.title%> <br>
   <strong stlye="margin-left:30px">Created By:</strong>  <%=article.user.email%> 
   <%if !article.likers.include? @current_user%>
  <strong><%= link_to 'Add to favourites', favourites_article_path(article) ,method: :put%> </strong>
  <%else%>
  <strong><%= link_to 'Remove from favourites', favourites_article_path(article),method: :delete, data: { confirm: 'Are you sure to remove it from favourite?' }%></strong>
  <%end%> 
    <hr>
 <%end%>

app/views/user/my_followed_list.html.erb
<p id="notice"><%= notice %></p>

<h1>Followed List</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Action</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @followed_list.each do |user| %>
      <tr>    
        <td><%= user.email%></td> 
        <td><%= link_to 'unfollow', unfollow_path(:id=>user.id),method: :delete, data: { confirm: 'Are you sure?' }%> </td> 
      </tr>
    <% end %>
  </tbody>
</table>

app/views/user/my_followees_articles.html.erb
<p id="notice"><%= notice %></p>
  
  <%@articles.each do |article| %>
 
  <strong> Title: </strong><%=article.title%>  
  <br>
  <strong> content: </strong><%=article.content%> 
  <br>
  <strong> created_by: </strong><%=article.user.email%> 
  <br>
  <%if !article.likers.include? @current_user%>
  <strong><%= link_to 'Add to favourites', favourites_article_path(article) ,method: :put%> </strong>
  <%else%>
  <strong><%= link_to 'Remove from favourites', favourites_article_path(article),method: :delete, data: { confirm: 'Are you sure to remove it from favourite?' }%></strong>
  <%end%> 
  <br>
  <strong>Favourite Count : </strong><%=article.count %>
  <hr> 
  <%end%>

app/views/user/my_followers_list.html.erb
<p id="notice"><%= notice %></p>

<h1>Followers List</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Action</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @followers_list.each do |user| %>
      <tr>
       <%if @current_user.id!=user.id%>
        <td><%= user.email%></td> 
        <%if !@current_user.followees.include? user%>
        <td><%= link_to 'follow', follow_path(:id=>user.id),method: :put%> </td>
        <%else%> 
        <td><%= link_to 'unfollow', unfollow_path(:id=>user.id),method: :delete, data: { confirm: 'Are you sure?' }%> </td> 
        <%end%>
      </tr>
    <% end %>
    <%end%>
  </tbody>
</table>