config/routes.rb
Rails.application.routes.draw do
  resources :articles do 
     member do
        put 'favourites'
        delete 'favourites'
     end  
   end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "signup" => "signup#new"
  post "signup" => "signup#create"
  get "signin" => "session#new"
  post "signin" => "session#create"
  delete "signout" => "session#destroy"
  get "favourite_articles" => "user#my_favourite"
  get "all_user" => "user#index"
  put "follow" => "user#follow"
  delete "unfollow" => "user#unfollow"
  get "followees_articles" => "user#my_followees_articles"
  get "my_followers_list" => "user#my_followers_list"
  get "my_followed_list" => "user#my_followed_list"


   # Api Routes
   namespace :api do
    namespace :v1 do
      resources :articles do 
        member do
           put 'favourites'
           delete 'favourites'
        end  
      end
      post "signup" => "signup#create"
      get "users" => "user#index"
      post "signin" => "authentication#authenticate" 
      get "favourite_articles" => "user#my_favourite"
      put "follow" => "user#follow"
      delete "unfollow" => "user#unfollow"
      get "followees_articles" => "user#my_followees_articles"
      get "my_followers_list" => "user#my_followers_list"
      get "my_followed_list" => "user#my_followed_list"
    end
  end


  root to: 'articles#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <% if @current_user %>
   <strong><%= link_to'Users', all_user_path%></strong>
   <strong style="margin-left:25px"><%= link_to'Articles', articles_path%></strong>
   <hr>
   <%end%>
  
   <% if !@current_user %>
   <strong> Join Us NOW !!</strong>
   <%else%>
   <strong><%= link_to'My favourites', favourite_articles_path%></strong>
   <strong style="margin-left:25px"><%= link_to'Signout',signout_path,method: :delete, data: { confirm: 'Are you sure?' }%></strong>
   <strong style="margin-left:80px"><%= @current_user.email %></strong>
   <hr>
   <strong><%=link_to 'Following',my_followed_list_path%> : <%= @current_user.count_followees %></strong>
   <strong style="margin-left:25px"><%=link_to 'My Followers',my_followers_list_path%> : <%= @current_user.count_followers %></strong>
   <strong style="margin-left:25px"><%= link_to 'Followees Articles',followees_articles_path %></strong>
   <hr>
   <%end%>
   <%= yield %>
  </body>
</html>
 